import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import ReactLenis, { useLenis } from "lenis/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <>
      <ReactLenis root></ReactLenis>
      <html lang="en" className={`min-h-screen antialiased ${sora.className}`}>
        <body className="flex flex-col min-h-screen p-7">{children}</body>
      </html>
    </>
  );
}
